<?php 
unset($_SESSION["equipo"]);
unset($_SESSION["cod_equipo"]);
unset($_SESSION["clave"]);
unset($_SESSION["entrenador"]);
unset($_SESSION["cod_entrenador"]);
unset($_SESSION["clavadista"]);
unset($_SESSION["clavadista2"]);
unset($_SESSION["clavadista3"]);
unset($_SESSION["clavadista4"]);
unset($_SESSION["cod_clavadista"]);
unset($_SESSION["cod_clavadista2"]);
unset($_SESSION["cod_clavadista3"]);
unset($_SESSION["cod_clavadista4"]);
unset($_SESSION["categoria"]);
unset($_SESSION["imagen"]);
unset($_SESSION["imagen2"]);
unset($_SESSION["imagen3"]);
unset($_SESSION["imagen4"]);
unset($_SESSION["modalidad"]);
unset($_SESSION["participa_extraof"]);
unset($_SESSION["saltos"]);
unset($_SESSION["preserie"]);
unset($_SESSION["modalidad"]);
?>